const config = {
  language: 'zh',
  defaultServerLanguage: 'zs',
  upcomingGameDefaultDays: 30,
  championGameDefaultDays: 30,
  resultGameDefaultDays: 3,
  resultGameMAXDays: 7,
  balanceHistoryDefaultDays: 7,
  balanceHistoryMAXDays: 30,
  betHistoryDefaultDays: 7,
  betHistoryMAXDays: 30,
  dayRangeFilterItems: [
    { label: '3 days', value: 3 },
    { label: '5 days', value: 5 },
    { label: '7 days', value: 7 },
    { label: '14 days', value: 14 },
    { label: '30 days', value: 30 },
    { label: '60 days', value: 60 },
  ],
  betHistoryBetTypeItems: [
    { label: 'All', value: 'all' },
    { label: 'Single', value: 'single' },
    { label: 'Multiple', value: 'multiple' },
    { label: 'System', value: 'system' },
  ],
  upcomingGameListTypeFilterItem: [
    { label: 'All', value: 1 },
    { label: 'Live', value: 2 },
  ],
  betHistoryDefaultBetType: 'all',
  upcomingGameDisplayMode: {
    line: 1,
    grid: 2,
  },
  upcomingGameFilter: {
    all: 1,
    live: 2,
  },
  alertsContent: {
    betCountLimitError: 'The Betslip items have reached the upper limit',
    loginStateError: 'Please login first',
    betslipStakeError: 'Please check betslip and stakes',
  },
  clearLocalStorageInNewVersion: true,
  alertMessageKeepTime: 5000,
  recommendGameStayTime: 5000,
  updateBalancePollingTime: 15000,
  updateNewsPollingTime: 60000,
  newsStayTime: 15000,
  serverReconnectingIntervalTime: 10000,
  betHistoryNoResultStateName: 'Unsettled',
  newsTypeMap: {
    1: 'system',
    2: 'activity',
  },
  oddsFormat: {
    decimal: { label: 'decimal', value: 'decimal' },
    // fractional: { label: 'fractional', value: 'fractional' },
    // hongkong: { label: 'hongkong', value: 'hongkong' },
    // malay: { label: 'malay', value: 'malay' },
  },
  defaultOddsFormat: 'decimal',
  betslipBetTypeItems: {
    single: { label: 'single', value: 'single' },
    multiple: { label: 'multiple', value: 'multiple' },
    system: { label: 'system', value: 'system' },
  },
  defaultBetType: 'single',
  gameListTabs: {
    upcoming: { label: 'Upcoming', value: '' },
    champion: { label: 'Champion', value: 'champion' },
    result: { label: 'Result', value: 'result' },
  },
  betslipPriceChangeRadioGroup: {
    ask: { value: 'ask', label: 'Always ask' },
    upper: { value: 'upper', label: 'Accept higher odds' },
    free: { value: 'free', label: 'Accept any odds' },
  },
  betslipPriceChangeCodeMap: {
    ask: 2,
    upper: 1,
    free: 2,
  },
  defaultPriceChangeHandleType: 'ask',
  balanceHistoryModalRowPerPage: 10,
  betHistoryModalRowPerPage: 10,
  newsModalRowPerPage: 10,
  sportIds: [74, 75, 76, 77, 78, 80, 82, 83, 157, 158, 164, 169, 176, 185],
  nonVersusMarketType: [
    'DoubleChance',
    'CorrectScore',
    'MatchResult',
    'GameLargestMultiKill',
    'P1XP2',
    'Game1LargestMultiKill',
    'Game2LargestMultiKill',
    'Game3LargestMultiKill',
    'Game4LargestMultiKill',
    'Game5LargestMultiKill',
    'Game1FirstDragonType',
    'Game2FirstDragonType',
    'Game3FirstDragonType',
    'Game4FirstDragonType',
    'Game5FirstDragonType',
    'GameFirstActiveRuneType',
  ],
  betTypeCodeMap: {
    single: 1,
    multiple: 2,
    system: 3,
  },
  stakeDecimalPlaceDisplay: 2,
  priceDecimalPlaceDisplay: 2,
  balanceDecimalPlaceDisplay: 3,
  betslipBetCountMAX: 16,
  betslipSystemCountMIN: 3,
  EventStatus: {
    GameCancel: 3,
    MarketCancel: 4,
    Win: 1,
    NoResult: 0,
  },
  LiveStatus: {
    NotAvailable: 0,
    Available: 1,
    Completed: 2,
    Cancelled: 3,
  },
  MatchStatus: {
    NotStarted: 0,
    Started: 1,
    Completed: 2,
    Canceled: 3,
  },
  serverCode: {
    OK: 0,
    LoginFailed: 1002,
    ProductionNotOpen: 1004,
    ProductionMaintain: 1005,
    InsufficientBalance: 2002,
    SelectionNotExists: 2004,
  },
  balanceNotEnoughCode: 2002,
  langMap: {
    en: 'en',
    id: 'en',
    ko: 'en',
    ms: 'en',
    th: 'en',
    vi: 'en',
    zs: 'zh',
    ja: 'ja',
  },
  teamIconCdnUrl: 'https://cdn.rixinmould.com/images/b/',
};

module.exports = config;
